trigger:
  - main

pr:
  - main

# 定义构建代理池（使用Azure托管的Ubuntu代理）
pool:
  vmImage: 'ubuntu-latest'

# 定义变量（可根据项目调整）
variables:
  # Java版本
  JAVA_VERSION: '17'
  # Maven/Gradle构建输出目录
  BUILD_OUTPUT_DIR: 'target'
  # 项目打包后的jar/war名称（根据实际情况修改）
  ARTIFACT_NAME: 'my-java-app'
  # 构建类型（可选：maven/gradle）
  BUILD_TOOL: 'maven'

# 构建步骤
steps:
  # 步骤1：安装指定版本的Java
  - task: JavaToolInstaller@0
    displayName: '安装 Java $(JAVA_VERSION)'
    inputs:
      versionSpec: '$(JAVA_VERSION)'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # 步骤2：根据构建工具选择构建命令（Maven）
  - task: Maven@4
    displayName: 'Maven 清理、编译、测试、打包'
    condition: eq(variables.BUILD_TOOL, 'maven')
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests=false'  # 不跳过测试（如需跳过改为true）
      publishJUnitResults: true     # 自动发布JUnit测试结果到Azure DevOps
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '$(JAVA_VERSION)'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false  # 若非Azure Artifacts私服，设为false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false   # 如需SonarQube代码分析，设为true

  # 步骤3：发布构建产物（jar/war包）到Azure Pipeline
  - task: PublishBuildArtifacts@1
    displayName: '发布构建产物'
    inputs:
      PathtoPublish: '$(BUILD_OUTPUT_DIR)'
      ArtifactName: '$(ARTIFACT_NAME)'
      publishLocation: 'Container'

  # 可选步骤4：部署到Azure App Service（如需要部署）
  - task: AzureWebApp@1
    displayName: '部署到Azure App Service'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  # 仅main分支成功构建后部署
    inputs:
      azureSubscription: '你的Azure服务连接名称'  # 需提前在Azure DevOps配置
      appType: 'webApp'
      appName: '你的App Service名称'
      package: '$(BUILD_OUTPUT_DIR)/*.jar'  # 适配jar包，若为war包改为*.war
      runtimeStack: 'JAVA|17-java17'        # 对应Java版本