trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  JAVA_VERSION: '17'

steps:
  # 默认就会 checkout GitHub 公有仓库
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '$(JAVA_VERSION)'
      architecture: x64

  - task: Maven@4
    inputs:
      mavenPomFile: pom.xml
      goals: clean verify
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
